# Example yml file for automation
name: Example Workflow

on:
  workflow_dispatch:

jobs:
  example_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Get our files
        uses: actions/checkout@v2
      - name: Check out the VM
        run: |
          echo $ ls -la
          ls -la
          echo $ whoami
          whoami
      - name: fetch keys
        uses: shimataro/ssh-key-action/@v2
        with:
          key: ${{secrets.CASSINI_DEPLOYMENT_KEY}}$
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: login
        run : |
          echo $ ssh redball@cassini.cs.kent.edu
          ssh redball@cassini.cs.kent.edu

          echo $ ssh redball@cassini.cs.kent.edu 
          ssh redball@cassini.cs.kent.edu

